services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: stockpass
      POSTGRES_DB: stocks
    ports: ["5433:5432"]
  backend:
    build: ./backend
    env_file: ./backend/.env
    environment:
      DB_URL: postgresql+psycopg://postgres:stockpass@db:5432/stocks
    ports: ["8000:8000"]
    depends_on: [db]
  frontend:
    build: ./frontend
    ports: ["5173:5173"]